Import("env")

libs = ["check", "m", "pthread", "rt",
        "subunit", "data_structures"]


dyn_array_test = env.Program("dyn_array_test", ["dyn_array.c"],
                             LIBS=libs,
                             LIBPATH=["#build/"],
                             CPPPATH=["#src/"])

linked_list_test = env.Program("linked_list_test", ["linked_list.c"],
                               LIBS=libs,
                               LIBPATH=["#build/"],
                               CPPPATH=["#src/"])

env.Alias("test", [dyn_array_test, linked_list_test])
